movieproject/movieapp/urls.py
from . import views
from django.urls import include, path
app_name='movieapp'

urlpatterns = [

  path('',views.index,name='index'), 
  path('movie/<int:movie_id>',views.detail,name='detail'),
  path('add/',views.add_movie,name='add_movie'),
  path('update/<int:id>/',views.update,name='update'),
  path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from . models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
    # return HttpResponse("ths is movie no %s" % movie_id)
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
          
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your movie name"><br>
    <input type="text" name="desc" placeholder="enter the movie description"><br>
    <input type="text" name="year" placeholder="enter the year"><br>
    <input type="file" name="img"><br>
    <input type="submit" name="Add"><br>
    {% endblock %}
</form>

movieproject/templates/base.html
{% load static %}
<html>
    <head>
        <title>index page</title>
        <!-- Image and text -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <link rel="stylesheet" href="{% static 'style.css' %}">
      {% comment %} <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt=""> {% endcomment %}
      Online Movie Store
    </a>
  </nav>

    </head>
    <body> 
        {% block body %}
        {% endblock %}
    </body>

    </html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
   <form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?<input class="btn btn-primary" type="submit">
    {% endblock %}
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
<html>
    <head>
        <title>Detail page</title>
    </head>
        <body>
            
            {% block body %}
          
            <div calss="container">
                <div class="row">
                    <div class="col-md-6">

            <img src="{{movie.img.url}}" width="200" height="200">
                    </div>
                    <div class="col-md-6">

           <h2> {{movie.name}}</h2>
           <h4> {{movie.desc}}</h4>
            <h4>{{movie.year}}</h4>
            
           
            
            <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-primary" href="{% url 'movieapp:delete' movie.id %}">delete</a>
                    </div>

                </div>
            </div>
            
            {% endblock %}
            {% comment %} <a href="{% url 'detail' i.id%}">
                {{i.name}}<br> {% endcomment %}
        </body>
       
   
</html>

movieproject/templates/edit.html
{% extends 'base.html'%}
{% block body %}
<form method="POST" enctype="multipart/form=data">
{% csrf_token %}

{{form.as_p}}<br>
<input class="btn btn-primary" type="submit"><br>
{% endblock %}

movieproject/templates/index.html
    
     
{% extends 'base.html'%}

{% block body %}
        {% for i in movie_list %}
        {% comment %} <a href="movie/{{i.id}}"> {% endcomment %}
            {% comment %} <a href="http://www.google.com"> {% endcomment %}
            {% comment %} {{i.name}}<br> {% endcomment %}
            <div class="col-md-6">
            <img src="{{i.img.url}}" width="100" height="100">
            <a href="{% url  'movieapp:detail' i.id %}">{{i.name}}</a><br>
            </div>  
                
        {% endfor %}
        {% endblock %}
   